/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts.index'
import { Route as ThoughtsThoughtIdRouteImport } from './routes/thoughts_.$thoughtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsThoughtIdRoute = ThoughtsThoughtIdRouteImport.update({
  id: '/thoughts_/$thoughtId',
  path: '/thoughts/$thoughtId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thoughts/$thoughtId': typeof ThoughtsThoughtIdRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thoughts/$thoughtId': typeof ThoughtsThoughtIdRoute
  '/thoughts': typeof ThoughtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/thoughts_/$thoughtId': typeof ThoughtsThoughtIdRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/legal' | '/privacy-policy' | '/thoughts/$thoughtId' | '/thoughts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legal' | '/privacy-policy' | '/thoughts/$thoughtId' | '/thoughts'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/privacy-policy'
    | '/thoughts_/$thoughtId'
    | '/thoughts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ThoughtsThoughtIdRoute: typeof ThoughtsThoughtIdRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts_/$thoughtId': {
      id: '/thoughts_/$thoughtId'
      path: '/thoughts/$thoughtId'
      fullPath: '/thoughts/$thoughtId'
      preLoaderRoute: typeof ThoughtsThoughtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ThoughtsThoughtIdRoute: ThoughtsThoughtIdRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
