/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaysIndexRouteImport } from './routes/essays/index'
import { Route as EssaysEssayKeyRouteImport } from './routes/essays/$essayKey'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIndexRoute = EssaysIndexRouteImport.update({
  id: '/essays/',
  path: '/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysEssayKeyRoute = EssaysEssayKeyRouteImport.update({
  id: '/essays/$essayKey',
  path: '/essays/$essayKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/essays/$essayKey': typeof EssaysEssayKeyRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/essays/$essayKey': typeof EssaysEssayKeyRoute
  '/essays': typeof EssaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/essays/$essayKey': typeof EssaysEssayKeyRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/legal'
    | '/privacy-policy'
    | '/essays/$essayKey'
    | '/essays/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/legal'
    | '/privacy-policy'
    | '/essays/$essayKey'
    | '/essays'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/legal'
    | '/privacy-policy'
    | '/essays/$essayKey'
    | '/essays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  LegalRoute: typeof LegalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  EssaysEssayKeyRoute: typeof EssaysEssayKeyRoute
  EssaysIndexRoute: typeof EssaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/': {
      id: '/essays/'
      path: '/essays'
      fullPath: '/essays/'
      preLoaderRoute: typeof EssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$essayKey': {
      id: '/essays/$essayKey'
      path: '/essays/$essayKey'
      fullPath: '/essays/$essayKey'
      preLoaderRoute: typeof EssaysEssayKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  LegalRoute: LegalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  EssaysEssayKeyRoute: EssaysEssayKeyRoute,
  EssaysIndexRoute: EssaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
